In [1]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('D:/Master Degree at NYCU/1. Slides and Homeworks/Spring_2024/1. FinTech/JN/USArrests.csv')

# Display the first few rows
df.head()

Unnamed: 0  Murder  Assault  UrbanPop  Rape
0     Alabama    13.2      236        58  21.2
1      Alaska    10.0      263        48  44.5
2     Arizona     8.1      294        80  31.0
3    Arkansas     8.8      190        50  19.5
4  California     9.0      276        91  40.6

In [5]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Step 3: Drop the non-numerical column (state names)
# Assuming the first column contains state names
df_numeric = df.drop(columns=['Unnamed: 0'])  # Adjust this if your column has a specific name like 'State'

# Step 4: Standardize the data (mean=0, variance=1)
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_numeric)

# Step 5: Perform PCA to extract the principal components
pca = PCA(n_components=4)  # we want the first 4 principal components
pca.fit(df_scaled)

# Step 6: Get the loading vectors (principal component coefficients)
loading_vectors = pca.components_

# Display the first to fourth principal component loading vectors
for i in range(4):
    print(f"Principal Component {i+1} loading vector:")
    print(loading_vectors[i])
    print()

Principal Component 1 loading vector:
[0.53589947 0.58318363 0.27819087 0.54343209]

Principal Component 2 loading vector:
[ 0.41818087  0.1879856  -0.87280619 -0.16731864]

Principal Component 3 loading vector:
[-0.34123273 -0.26814843 -0.37801579  0.81777791]

Principal Component 4 loading vector:
[ 0.6492278  -0.74340748  0.13387773  0.08902432]



In [11]:
import numpy as np  # Make sure numpy is imported

# Step 5: Compute the covariance matrix
cov_matrix = np.cov(df_scaled.T)

# Step 6: Perform eigenvalue decomposition using np.linalg.eig()
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Step 7: Sort the eigenvectors by eigenvalues in descending order
# The eigenvalues are already paired with their eigenvectors
sorted_indices = np.argsort(eigenvalues)[::-1]
sorted_eigenvectors = eigenvectors[:, sorted_indices]

# Step 8: Display the first to fourth principal component loading vectors
for i in range(4):
    print(f"Principal Component {i+1} loading vector:")
    print(sorted_eigenvectors[:, i])
    print()

Principal Component 1 loading vector:
[0.53589947 0.58318363 0.27819087 0.54343209]

Principal Component 2 loading vector:
[ 0.41818087  0.1879856  -0.87280619 -0.16731864]

Principal Component 3 loading vector:
[-0.34123273 -0.26814843 -0.37801579  0.81777791]

Principal Component 4 loading vector:
[ 0.6492278  -0.74340748  0.13387773  0.08902432]



In [13]:
# Step 5: Perform Singular Value Decomposition (SVD)
U, S, VT = np.linalg.svd(df_scaled)

# Step 6: Get the loading vectors (principal component coefficients)
# The loading vectors are given by the right singular vectors
loading_vectors = VT.T  # Transpose VT to get the correct shape

# Step 7: Display the first to fourth principal component loading vectors
for i in range(4):
    print(f"Principal Component {i+1} loading vector:")
    print(loading_vectors[:, i])
    print()

Principal Component 1 loading vector:
[-0.53589947 -0.58318363 -0.27819087 -0.54343209]

Principal Component 2 loading vector:
[ 0.41818087  0.1879856  -0.87280619 -0.16731864]

Principal Component 3 loading vector:
[-0.34123273 -0.26814843 -0.37801579  0.81777791]

Principal Component 4 loading vector:
[ 0.6492278  -0.74340748  0.13387773  0.08902432]

