# HW0930Q2

### [PCA] Use the 'USArrests' data:

##### (a) Show the first to fourth principal component loadings vectors using PCA() function.

In [1]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import statsmodels.api as sm

df = sm.datasets.get_rdataset('USArrests', 'datasets').data

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)

pca = PCA(n_components=4)
pca.fit(df_scaled)

loadings = pca.components_
print(loadings)

[[ 0.53589947  0.58318363  0.27819087  0.54343209]
 [-0.41818087 -0.1879856   0.87280619  0.16731864]
 [-0.34123273 -0.26814843 -0.37801579  0.81777791]
 [-0.6492278   0.74340748 -0.13387773 -0.08902432]]


##### (b) Use np.linalg.eig() to find the first to fourth principal component loadings vectors.

In [2]:
import numpy as np

cov_matrix = np.cov(df_scaled.T)

eig_values, eig_vectors = np.linalg.eig(cov_matrix)

print(eig_vectors[:,:])

[[ 0.53589947  0.41818087  0.6492278  -0.34123273]
 [ 0.58318363  0.1879856  -0.74340748 -0.26814843]
 [ 0.27819087 -0.87280619  0.13387773 -0.37801579]
 [ 0.54343209 -0.16731864  0.08902432  0.81777791]]


##### (c) Use np.linalg.svd() to find the first to fourth principal component loadings vectors.

In [3]:
U, S, Vt = np.linalg.svd(df_scaled)

print(Vt[:])

[[-0.53589947 -0.58318363 -0.27819087 -0.54343209]
 [-0.41818087 -0.1879856   0.87280619  0.16731864]
 [ 0.34123273  0.26814843  0.37801579 -0.81777791]
 [ 0.6492278  -0.74340748  0.13387773  0.08902432]]


##### (d) Are those from (a), (b), and (c) exactly the same? Why or why not?

Yes, although the loading vectors may differ in arrangement and sign, they can still be regarded as equivalent variables.