# (a) Show the first to fourth principal component loadings using PCA function

In [1]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


file_path = r'C:\Users\坤達\Downloads\USArrests.csv'
USArrests = pd.read_csv(file_path, index_col=0)

#Standarliz the data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(USArrests)

#PCA
pca = PCA(n_components=4) 
pca.fit(scaled_data)


loadings = pca.components_
print('PCA Loadings:')
print(loadings)

PCA Loadings:
[[ 0.53589947  0.58318363  0.27819087  0.54343209]
 [-0.41818087 -0.1879856   0.87280619  0.16731864]
 [-0.34123273 -0.26814843 -0.37801579  0.81777791]
 [-0.6492278   0.74340748 -0.13387773 -0.08902432]]


# (b) Use np.linalg.eig() function to find the first to fourth principal component loadings

In [4]:
import numpy as np

#Covariance matrix
cov_matrix = np.cov(scaled_data.T)

#Eigen decomposition
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print('Eigenvectors (first 4):')
print(eigenvectors[:, :4])


Eigenvectors (first 4):
[[ 0.53589947  0.41818087  0.6492278  -0.34123273]
 [ 0.58318363  0.1879856  -0.74340748 -0.26814843]
 [ 0.27819087 -0.87280619  0.13387773 -0.37801579]
 [ 0.54343209 -0.16731864  0.08902432  0.81777791]]


# (c) Use np.linalg.svd() function to find the first to fourth principal component loadings

In [11]:
#SVD
U, S, Vt = np.linalg.svd(scaled_data)

svd_loadings = Vt[:4, :4]
print('SVD Loadings:')
print(svd_loadings)


SVD Loadings:
[[-0.53589947 -0.58318363 -0.27819087 -0.54343209]
 [-0.41818087 -0.1879856   0.87280619  0.16731864]
 [ 0.34123273  0.26814843  0.37801579 -0.81777791]
 [ 0.6492278  -0.74340748  0.13387773  0.08902432]]


# (d) Are the results from (a), (b), and (c) exactly the same? Why or why not?

Same but not identical.
PCA function typically returns loadings that are scaled to have unit variance, while np.linalg.eig() gives raw eigenvectors, and SVD decomposition might return vectors with signs flipped.
