In [7]:
###read data
import pandas as pd

file_path ="USArrests拷貝.csv"
df = pd.read_csv(file_path)
print(df.info())
print(df.describe())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   rownames  50 non-null     object 
 1   Murder    50 non-null     float64
 2   Assault   50 non-null     int64  
 3   UrbanPop  50 non-null     int64  
 4   Rape      50 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 1.8+ KB
None
         Murder     Assault   UrbanPop       Rape
count  50.00000   50.000000  50.000000  50.000000
mean    7.78800  170.760000  65.540000  21.232000
std     4.35551   83.337661  14.474763   9.366385
min     0.80000   45.000000  32.000000   7.300000
25%     4.07500  109.000000  54.500000  15.075000
50%     7.25000  159.000000  66.000000  20.100000
75%    11.25000  249.000000  77.750000  26.175000
max    17.40000  337.000000  91.000000  46.000000
     rownames  Murder  Assault  UrbanPop  Rape
0     Alabama    13.2      236        58  21.2
1      Alaska 

In [10]:
###(a) 
from sklearn.decomposition import PCA
import pandas as pd

##不要欄位名稱 哪一州
X = df.iloc[:, 1:].values 
##PCA
pca = PCA(n_components = 4)
pca.fit(X)
##loading 
pca_loadings = pca.components_.T
print("PCA 負載向量（前四個主成分）：\n", pca_loadings)

PCA 負載向量（前四個主成分）：
 [[ 0.04170432  0.04482166  0.07989066  0.99492173]
 [ 0.99522128  0.05876003 -0.06756974 -0.0389383 ]
 [ 0.04633575 -0.97685748 -0.20054629  0.05816914]
 [ 0.0751555  -0.20071807  0.97408059 -0.07232502]]


In [11]:
##(b) np.lonalg.eig() 特徵值分解前面四個

import numpy as np
# 計算資料矩陣的協方差矩陣
cov_matrix = np.cov(X.T)

# 使用 np.linalg.eig() 求特徵值和特徵向量
eigen_values, eigen_vectors = np.linalg.eig(cov_matrix)

# 顯示前四個特徵向量（主成分負載向量）
print("特徵值分解（eig）負載向量（前四個主成分）：\n", eigen_vectors[:, :4])

特徵值分解（eig）負載向量（前四個主成分）：
 [[ 0.04170432  0.04482166 -0.99492173  0.07989066]
 [ 0.99522128  0.05876003  0.0389383  -0.06756974]
 [ 0.04633575 -0.97685748 -0.05816914 -0.20054629]
 [ 0.0751555  -0.20071807  0.07232502  0.97408059]]


In [12]:
##(c)np.linalg.svd() 奇異值分解前面四個
# 使用 np.linalg.svd() 進行奇異值分解 （X=U⋅S⋅Vt)
U, S, VT = np.linalg.svd(X)

# 取出右奇異向量（VT），即主成分負載向量
print("奇異值分解（svd）負載向量（前四個主成分）：\n", VT.T[:, :4])

奇異值分解（svd）負載向量（前四個主成分）：
 [[-0.04239181  0.01616262 -0.06588426  0.99679535]
 [-0.94395706  0.3206858   0.0665517  -0.04094568]
 [-0.30842767 -0.93845891  0.15496743  0.01234261]
 [-0.10963744 -0.12725666 -0.98347101 -0.06760284]]


In [ ]:
##(d) (a)、(b)、(c) 的負載向量結果理論上應該相同，
##但因計算方法不同而有符號或數值上的微小差異。
##根本原因在於三種方法的內部算法和矩陣分解策略不同。
##PCA矩陣進行的特徵值分解。
##因此，它和 np.linalg.eig() 的結果通常相同，但方向可能相反（即符號可能不同
##(d) The loading vectors from (a), (b), and (c) should be same  
#However, due to differences in computation methods, 
#they may have minor variations in sign or numerical precision. 
#The main reason lies in the different internal algorithms and matrix decomposition strategies.
#PCA is based on the eigen decomposition of the covariance matrix. 
#Therefore, its result is generally the same as that of np.linalg.eig(), 
#but the directions may differ (i.e., the signs might be opposite).